name: Send submodule updates to parent repo

on:
  workflow_dispatch:
  push:
    branches: 
      - master

jobs:
  dispatch-parent-workflows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hearsaycorp/repository-dispatch-action@1.0.1
        with: 
          REPOSITORY: hearsaycorp/web-platform-team-directory
          EVENT_TYPE: on-demand-submodule-update
          HEARSAYDEV_PAT: ${{ secrets.HEARSAYDEV_PAT }}